version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: subscription_api_mysql_db
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME:-subscription_api_db}
      MYSQL_USER: ${DB_USER:-db_app_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-db_app_password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-a_very_secret_root_password_CHANGE_ME}
    volumes:
      - mysql_data_subscription_api:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u${DB_USER:-db_app_user}",
          "-p${DB_PASSWORD:-db_app_password}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscription_api_web
    ports:
      - "${FLASK_RUN_PORT:-5001}:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_APP: run.py
      FLASK_CONFIG: ${FLASK_CONFIG:-production}
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      DATABASE_URL: mysql+pymysql://${DB_USER:-db_app_user}:${DB_PASSWORD:-db_app_password}@db:3306/${DB_NAME:-subscription_api_db}
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql_data_subscription_api:

networks:
  app-network:
    driver: bridge
